# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "helloworld.ipynb",
         "PUBLIC_KEY": "tidb_connect.ipynb",
         "PRIVATE_KEY": "tidb_connect.ipynb",
         "REGION": "tidb_connect.ipynb",
         "APP_ID": "tidb_connect.ipynb",
         "cluster_id": "tidb_connect.ipynb",
         "database": "tidb_connect.ipynb",
         "Chat2QueryAPI": "tidb_connect.ipynb",
         "print_pretty_result": "tidb_connect.ipynb"}

modules = ["helloworld_example.py",
           "tidb_connect.py"]

doc_url = "https://your_github_username.github.io/your_repository_name/"

git_url = "https://github.com/northpr/jupyternb-template"

def custom_doc_links(name): return None
